version: '3.8'

services:
    phpmyadmin:
        image: phpmyadmin:5.2.1-apache
        ports:
            - 8080:80
        secrets:
            - db-user
            - db-password
            - db-root-password
        environment:
            MYSQL_USER_FILE: /run/secrets/db-user
            MYSQL_PASSWORD_FILE: /run/secrets/db-password
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-root-password
            PMA_ARBITRARY: "1"
        depends_on:
            - mysql
        networks:
            - backend
        deploy:
            replicas: 1
    app:
        image: wordpress:6.2.2-php8.2-apache
        ports:
            - 80:80
            - 443:443
        secrets:
            - db-user
            - db-password
        environment:
            WORDPRESS_DB_HOST: mysql:3306
            WORDPRESS_DB_USER_FILE: /run/secrets/db-user
            WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db-password
            WORDPRESS_DB_NAME: db
        volumes:
            - app:/var/www/html
        depends_on:
            - mysql
        networks:
            - backend
        deploy:
            replicas: 1
    mysql:
        image: mysql:8.0.33
        secrets:
            - db-user
            - db-password
            - db-root-password
        environment:
            MYSQL_USER_FILE: /run/secrets/db-user
            MYSQL_PASSWORD_FILE: /run/secrets/db-password
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-root-password
            MYSQL_DATABASE: db
        volumes:
            - db:/var/lib/mysql
        networks:
            - backend
        deploy:
            replicas: 1

secrets:
    admin-user:
        external: true
    admin-password:
        external: true
    admin-email:
        external: true
    db-user:
        external: true
    db-password:
        external: true
    db-root-password:
        external: true
volumes:
    app: {}
    db: {}
networks:
    backend:
        driver: overlay
          